(define (problem Keys-0)
(:domain find_key)
(:objects
	l0 - LEVEL
	l1 - LEVEL
)

(:init
	(resolve-axioms)
	(lev l0)
	(next l0 l1)
	(current_kb basis_kb)
	(part-of basic basis_kb)
	(m basic)
	(robot_at robot loc_0 basic)
	(gripper_empty robot  basic)
	(clear object_0 basic)
	(clear object_1 basic)
	(connected loc_0 loc_1)
	(connected loc_1 loc_0)
	(= (distance loc_0 loc_1) 10)
	(= (distance loc_1 loc_0) 10)
	(connected loc_1 loc_0)
	(connected loc_0 loc_1)
	(= (distance loc_1 loc_0) 10)
	(= (distance loc_0 loc_1) 10)
	(part-of basic basis_kb)
	(parent basis_kb kb_location_object_0)
	(parent basis_kb kb_location_object_1)
	(part-of skb_location_object_0_loc_0_type_0_pickupable kb_location_object_0)
	(object_at object_0 loc_0 skb_location_object_0_loc_0_type_0_pickupable)
	(is_of_type object_0 type_0 skb_location_object_0_loc_0_type_0_pickupable)
	(can_pickup object_0 skb_location_object_0_loc_0_type_0_pickupable)
	(part-of skb_location_object_0_loc_0_type_0_pushable kb_location_object_0)
	(object_at object_0 loc_0 skb_location_object_0_loc_0_type_0_pushable)
	(is_of_type object_0 type_0 skb_location_object_0_loc_0_type_0_pushable)
	(can_push object_0 skb_location_object_0_loc_0_type_0_pushable)
	(part-of skb_location_object_0_loc_0_type_1_pickupable kb_location_object_0)
	(object_at object_0 loc_0 skb_location_object_0_loc_0_type_1_pickupable)
	(is_of_type object_0 type_1 skb_location_object_0_loc_0_type_1_pickupable)
	(can_pickup object_0 skb_location_object_0_loc_0_type_1_pickupable)
	(part-of skb_location_object_0_loc_0_type_1_pushable kb_location_object_0)
	(object_at object_0 loc_0 skb_location_object_0_loc_0_type_1_pushable)
	(is_of_type object_0 type_1 skb_location_object_0_loc_0_type_1_pushable)
	(can_push object_0 skb_location_object_0_loc_0_type_1_pushable)
	(part-of skb_location_object_0_loc_1_type_0_pickupable kb_location_object_0)
	(object_at object_0 loc_1 skb_location_object_0_loc_1_type_0_pickupable)
	(is_of_type object_0 type_0 skb_location_object_0_loc_1_type_0_pickupable)
	(can_pickup object_0 skb_location_object_0_loc_1_type_0_pickupable)
	(part-of skb_location_object_0_loc_1_type_0_pushable kb_location_object_0)
	(object_at object_0 loc_1 skb_location_object_0_loc_1_type_0_pushable)
	(is_of_type object_0 type_0 skb_location_object_0_loc_1_type_0_pushable)
	(can_push object_0 skb_location_object_0_loc_1_type_0_pushable)
	(part-of skb_location_object_0_loc_1_type_1_pickupable kb_location_object_0)
	(object_at object_0 loc_1 skb_location_object_0_loc_1_type_1_pickupable)
	(is_of_type object_0 type_1 skb_location_object_0_loc_1_type_1_pickupable)
	(can_pickup object_0 skb_location_object_0_loc_1_type_1_pickupable)
	(part-of skb_location_object_0_loc_1_type_1_pushable kb_location_object_0)
	(object_at object_0 loc_1 skb_location_object_0_loc_1_type_1_pushable)
	(is_of_type object_0 type_1 skb_location_object_0_loc_1_type_1_pushable)
	(can_push object_0 skb_location_object_0_loc_1_type_1_pushable)
	(part-of skb_location_object_1_loc_0_type_0_pickupable kb_location_object_1)
	(object_at object_1 loc_0 skb_location_object_1_loc_0_type_0_pickupable)
	(is_of_type object_1 type_0 skb_location_object_1_loc_0_type_0_pickupable)
	(can_pickup object_1 skb_location_object_1_loc_0_type_0_pickupable)
	(part-of skb_location_object_1_loc_0_type_0_pushable kb_location_object_1)
	(object_at object_1 loc_0 skb_location_object_1_loc_0_type_0_pushable)
	(is_of_type object_1 type_0 skb_location_object_1_loc_0_type_0_pushable)
	(can_push object_1 skb_location_object_1_loc_0_type_0_pushable)
	(part-of skb_location_object_1_loc_0_type_1_pickupable kb_location_object_1)
	(object_at object_1 loc_0 skb_location_object_1_loc_0_type_1_pickupable)
	(is_of_type object_1 type_1 skb_location_object_1_loc_0_type_1_pickupable)
	(can_pickup object_1 skb_location_object_1_loc_0_type_1_pickupable)
	(part-of skb_location_object_1_loc_0_type_1_pushable kb_location_object_1)
	(object_at object_1 loc_0 skb_location_object_1_loc_0_type_1_pushable)
	(is_of_type object_1 type_1 skb_location_object_1_loc_0_type_1_pushable)
	(can_push object_1 skb_location_object_1_loc_0_type_1_pushable)
	(part-of skb_location_object_1_loc_1_type_0_pickupable kb_location_object_1)
	(object_at object_1 loc_1 skb_location_object_1_loc_1_type_0_pickupable)
	(is_of_type object_1 type_0 skb_location_object_1_loc_1_type_0_pickupable)
	(can_pickup object_1 skb_location_object_1_loc_1_type_0_pickupable)
	(part-of skb_location_object_1_loc_1_type_0_pushable kb_location_object_1)
	(object_at object_1 loc_1 skb_location_object_1_loc_1_type_0_pushable)
	(is_of_type object_1 type_0 skb_location_object_1_loc_1_type_0_pushable)
	(can_push object_1 skb_location_object_1_loc_1_type_0_pushable)
	(part-of skb_location_object_1_loc_1_type_1_pickupable kb_location_object_1)
	(object_at object_1 loc_1 skb_location_object_1_loc_1_type_1_pickupable)
	(is_of_type object_1 type_1 skb_location_object_1_loc_1_type_1_pickupable)
	(can_pickup object_1 skb_location_object_1_loc_1_type_1_pickupable)
	(part-of skb_location_object_1_loc_1_type_1_pushable kb_location_object_1)
	(object_at object_1 loc_1 skb_location_object_1_loc_1_type_1_pushable)
	(is_of_type object_1 type_1 skb_location_object_1_loc_1_type_1_pushable)
	(can_push object_1 skb_location_object_1_loc_1_type_1_pushable)
)
(:goal (and
	(tidy object_0 basic)
	(tidy object_1 basic)
)
)
)
