(raminificate)
(drive-truck-loc-ap truck_0_city_0 loc_1_city_0 airport_0_city_0 city_0)
(assume_knowledge basis_kb kb_package_city_0_0)
(raminificate)
(drive-truck-ap-loc truck_0_city_0 airport_0_city_0 loc_1_city_0 city_0)
(sense-package-loc-t package_city_0_0 loc_1_city_0 truck_0_city_0 l0 l1 kb_package_city_0_0)
(raminificate)
(load-truck-loc package_city_0_0 truck_0_city_0 loc_1_city_0 city_0)
(drive-truck-loc-ap truck_0_city_0 loc_1_city_0 airport_0_city_0 city_0)
(unload-truck-ap package_city_0_0 truck_0_city_0 airport_0_city_0 city_0)
(pop l1 l0)
(raminificate)
(drive-truck-loc-ap truck_0_city_0 loc_1_city_0 airport_0_city_0 city_0)
(drive-truck-ap-loc truck_0_city_0 airport_0_city_0 loc_0_city_0 city_0)
(load-truck-loc package_city_0_0 truck_0_city_0 loc_0_city_0 city_0)
(drive-truck-loc-ap truck_0_city_0 loc_0_city_0 airport_0_city_0 city_0)
(unload-truck-ap package_city_0_0 truck_0_city_0 airport_0_city_0 city_0)
(shed_knowledge kb_package_city_0_0 basis_kb)
