(define (problem Keys-0)
(:domain find_key)
(:objects
	l0 - LEVEL
	l1 - LEVEL
)

(:init
	(resolve-axioms)
	(lev l0)
	(next l0 l1)
	(current_kb basis_kb)
	(part-of basic basis_kb)
	(m basic)
	(garbage-at colour_0_garbage loc_0)
	(garbage-color colour_0_garbage colour_0)
	(garbage-at colour_1_garbage loc_1)
	(garbage-color colour_1_garbage colour_1)
	(adj loc_0 loc_1)
	(adj loc_1 loc_0)
	(adj loc_1 loc_0)
	(adj loc_0 loc_1)
	(part-of basic basis_kb)
	(at loc_0 basic)
	(parent basis_kb kb_location_ball_0)
	(parent basis_kb kb_colour_ball_0)
	(parent basis_kb kb_location_ball_1)
	(parent basis_kb kb_colour_ball_1)
	(part-of kb_location_ball_0_loc_0 kb_location_ball_0)
	(obj-at ball_0 loc_0 kb_location_ball_0_loc_0)
	(at loc_0 kb_location_ball_0_loc_0)
	(part-of kb_location_ball_0_loc_0_loc_1 kb_location_ball_0)
	(obj-at ball_0 loc_1 kb_location_ball_0_loc_0_loc_1)
	(at loc_0 kb_location_ball_0_loc_0_loc_1)
	(part-of kb_colour_ball_0_colour_0 kb_colour_ball_0)
	(color ball_0 colour_0 kb_colour_ball_0_colour_0)
	(at loc_0 kb_colour_ball_0_colour_0)
	(part-of kb_colour_ball_0_colour_0_colour_1 kb_colour_ball_0)
	(color ball_0 colour_1 kb_colour_ball_0_colour_0_colour_1)
	(at loc_0 kb_colour_ball_0_colour_0_colour_1)
	(part-of kb_location_ball_1_loc_0 kb_location_ball_1)
	(obj-at ball_1 loc_0 kb_location_ball_1_loc_0)
	(at loc_0 kb_location_ball_1_loc_0)
	(part-of kb_location_ball_1_loc_0_loc_1 kb_location_ball_1)
	(obj-at ball_1 loc_1 kb_location_ball_1_loc_0_loc_1)
	(at loc_0 kb_location_ball_1_loc_0_loc_1)
	(part-of kb_colour_ball_1_colour_0 kb_colour_ball_1)
	(color ball_1 colour_0 kb_colour_ball_1_colour_0)
	(at loc_0 kb_colour_ball_1_colour_0)
	(part-of kb_colour_ball_1_colour_0_colour_1 kb_colour_ball_1)
	(color ball_1 colour_1 kb_colour_ball_1_colour_0_colour_1)
	(at loc_0 kb_colour_ball_1_colour_0_colour_1)
)
(:goal (and
	(trashed ball_0 basic)
	(trashed ball_1 basic)
)
)
)
